# Generated by Django 6.0.1 on 2026-02-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watch_Wallet_app', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
